insert into public.articles
  (source_id, guid, url, title, original_excerpt, author, published_at, summary_fr, themes, impact_level, impact_reason, enriched_at)
values
(
    (select id from public.sources where slug = 'search-engine-land'),
    'https://searchengineland.com/?p=485665',
    'https://searchengineland.com/google-working-on-fix-for-broken-favicons-in-google-search-485665',
    'Google working on fix for broken favicons in Google Search',
    'The issue started earlier this week and today, Friday, Google has confirmed it is a bug on its end.',
    'Barry Schwartz',
    '2026-08-21T18:43:34.000Z',
    'Google a confirmé un bug technique provoquant l''affichage de favicons cassés dans les résultats de recherche depuis le début de la semaine, et travaille actuellement sur un correctif.',
    ARRAY['technique']::text[],
    'mineur',
    'Bug d''affichage temporaire côté Google, sans changement de classement ni d''algorithme.',
    '2026-08-23T16:23:56.134Z'
  ),
(
    (select id from public.sources where slug = 'search-engine-land'),
    'https://searchengineland.com/?p=485367',
    'https://searchengineland.com/duane-forrester-20-for-20-interview-485367',
    'Duane Forrester: AI is rewriting SEO, but the mission is the same',
    'AI is forcing SEO to evolve fast, but Duane Forrester says success still comes from serving users, building trust, and learning continuously.',
    'Danny Goodwin',
    '2026-08-21T15:00:00.000Z',
    'Dans un entretien, Duane Forrester explique que l''IA transforme profondément les pratiques SEO, mais que l''objectif reste inchangé : servir les utilisateurs, construire la confiance et apprendre en continu.',
    ARRAY['ia-geo']::text[],
    'mineur',
    'Point de vue et retour d''expérience, sans annonce produit ou algorithmique concrète.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'search-engine-land'),
    'https://searchengineland.com/?p=485407',
    'https://searchengineland.com/build-eeat-checker-ai-coding-assistant-485407',
    'How to build an E-E-A-T checker with Claude Code',
    'Build an AI-powered E-E-A-T auditor that crawls websites, applies Google''s quality guidance and generates polished reports in minutes.',
    'James Allen',
    '2026-08-21T14:00:00.000Z',
    'Un tutoriel montre comment construire, avec Claude Code, un auditeur automatisé qui explore un site, applique les critères E-E-A-T de Google et génère un rapport de qualité en quelques minutes.',
    ARRAY['technique']::text[],
    'mineur',
    'Tutoriel pratique et outillage, pas une évolution de Google elle-même.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'search-engine-journal'),
    'https://www.searchenginejournal.com/seo-pulse-spam-update-generative-ui-ai-overviews-reddit-drop/586597/',
    'https://www.searchenginejournal.com/seo-pulse-spam-update-generative-ui-ai-overviews-reddit-drop/586597/',
    'Spam Update, Generative UI In AIOs, Reddit Drop – SEO Pulse via @sejournal, @MattGSouthern',
    'Google''s August spam update rolls out as generative UI reaches AI Overviews, websites get a new button, and Reddit''s ChatGPT citation share falls. The post Spam Update, Generative UI In AIOs, Reddit Drop – SEO Pulse appeared first on Search Engine Journal.',
    'Matt G. Southern',
    '2026-08-22T12:30:28.000Z',
    'Le déploiement de la mise à jour anti-spam d''août de Google coïncide avec l''arrivée d''une UI générative dans les AI Overviews, un nouveau bouton pour les sites, et une chute de la part de citations de Reddit dans ChatGPT.',
    ARRAY['core-update', 'ia-geo']::text[],
    'majeur',
    'Combine un déploiement de mise à jour anti-spam confirmé et une évolution des AI Overviews, deux signaux à surveiller de près.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'search-engine-journal'),
    'https://www.searchenginejournal.com/ai-mode-queries-are-3x-longer-the-case-for-leading-with-the-answer/585990/',
    'https://www.searchenginejournal.com/ai-mode-queries-are-3x-longer-the-case-for-leading-with-the-answer/585990/',
    'AI Mode Queries Are 3X Longer – Why Your Page Should Lead With The Answer via @sejournal, @gregjarboe',
    'One year of AI Mode data shows people asking questions, not typing fragments, which is why the lead-first paragraph now beats the narrative arc. The post AI Mode Queries Are 3X Longer – Why Your Page Should Lead With The Answer appeared first on Search Engine Journal.',
    'Greg Jarboe',
    '2026-08-21T19:00:14.000Z',
    'Une année de données sur l''AI Mode de Google montre que les internautes posent désormais de vraies questions plutôt que des mots-clés fragmentés, ce qui pousse à rédiger des pages qui répondent immédiatement plutôt que de dérouler un récit.',
    ARRAY['ia-geo', 'contenu']::text[],
    'mineur',
    'Analyse et recommandation de bonnes pratiques, sans changement produit annoncé par Google.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'search-engine-journal'),
    'https://www.searchenginejournal.com/the-house-doesnt-publish-its-tells/586359/',
    'https://www.searchenginejournal.com/the-house-doesnt-publish-its-tells/586359/',
    'The House Doesn’t Publish Its Tells via @sejournal, @pedrodias',
    'AI labs are buying pre-2022 books to avoid training on AI slop while quietly building text watermarking, exposing why content-at-scale strategies are a losing bet. The post The House Doesn’t Publish Its Tells appeared first on Search Engine Journal.',
    'Pedro Dias',
    '2026-08-21T14:30:45.000Z',
    'Les laboratoires d''IA rachèteraient des livres antérieurs à 2022 pour éviter d''entraîner leurs modèles sur du contenu généré par IA, tout en développant discrètement des techniques de tatouage numérique de texte, ce qui fragilise les stratégies de contenu produit en masse.',
    ARRAY['ia-geo', 'contenu']::text[],
    'mineur',
    'Tendance de fond et analyse prospective, pas un changement immédiat à appliquer.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'search-engine-roundtable'),
    'https://www.seroundtable.com/recap-08-21-2026-41922.html',
    'https://www.seroundtable.com/recap-08-21-2026-41922.html',
    'Daily Search Forum Recap: August 21, 2026',
    'Here is a recap of what happened in the search forums today...',
    'barry@rustybrick.com (Barry Schwartz)',
    '2026-08-21T14:00:00.000Z',
    'Récapitulatif quotidien des discussions des forums SEO : les sujets qui ont animé la communauté ce jour-là.',
    '{}',
    'mineur',
    'Format récapitulatif récurrent, sans annonce propre.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'search-engine-roundtable'),
    'https://www.seroundtable.com/google-search-console-crawl-stats-missing-41923.html',
    'https://www.seroundtable.com/google-search-console-crawl-stats-missing-41923.html',
    'Google Search Console Crawl Stats Missing Two Days Of Data',
    'The crawl stats report within Google Search Console has a data gap again. This time the crawl stats report is missing August 15 and 16th crawl data. Normally, Google can fix the data but Google has not yet fixed it.',
    'barry@rustybrick.com (Barry Schwartz)',
    '2026-08-21T13:12:00.000Z',
    'Le rapport de statistiques d''exploration de Google Search Console présente à nouveau un trou de données, cette fois les 15 et 16 août, non encore corrigé par Google.',
    ARRAY['technique']::text[],
    'mineur',
    'Anomalie de reporting dans un outil Google, sans impact direct sur le classement.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'search-engine-roundtable'),
    'https://www.seroundtable.com/video-08-21-2026-41915.html',
    'https://www.seroundtable.com/video-08-21-2026-41915.html',
    'Search News Buzz Video Recap: Google Unleashed The August 2026 Spam Update, Gemini 3.7 Powers AI Mode, Google and Microsoft Ads News & More',
    'Google has released its third spam update of the 2026 year, the August 2026 spam update this week and finished rolling out Friday morning at 4:50am. Google Search''s AI Mode is now being powered sometimes by...',
    'barry@rustybrick.com (Barry Schwartz)',
    '2026-08-21T12:01:00.000Z',
    'Google a terminé le déploiement de sa troisième mise à jour anti-spam de 2026 vendredi matin, et l''AI Mode de la recherche Google est désormais parfois propulsé par Gemini 3.7.',
    ARRAY['core-update', 'ia-geo']::text[],
    'majeur',
    'Confirmation du déploiement complet d''une mise à jour anti-spam Google et évolution du moteur derrière l''AI Mode.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'abondance'),
    'https://www.abondance.com/?p=2805701',
    'https://www.abondance.com/20260821-2805701-youtube-changement-comptage-vues-24-aout.html',
    'YouTube va compter les vues dès la première seconde à partir du 24 août',
    'Ce qu''il faut retenir : Dès le 24 août 2026, une vue sera comptée à la première frame de lecture, pour tous les formats (vidéos longues, Shorts, lives), au lieu des 30 secondes de visionnage auparavant requises pour les vidéos classiques. Les compteurs publics vont augmenter plus rapidement, mais un nouveau métrique baptisé "vues engagées" […] L’article "YouTube va compter les vues dès la première seconde à partir du 24 août" a été publié sur le site Abondance.',
    'Johan Sellitto',
    '2026-08-21T09:54:39.000Z',
    'À partir du 24 août 2026, YouTube comptera une vue dès la première frame de lecture pour tous les formats (longues vidéos, Shorts, lives), contre 30 secondes auparavant ; un nouvel indicateur de "vues engagées" est introduit en parallèle.',
    ARRAY['contenu']::text[],
    'mineur',
    'Changement de méthodologie de comptage sur YouTube, sans lien direct avec le classement Google Search.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'abondance'),
    'https://www.abondance.com/?p=2803528',
    'https://www.abondance.com/20260821-2803528-chatgpt-ads-lancement-europe.html',
    'ChatGPT Ads arrive en Europe : la publicité s’invite dans vos conversations avec l’IA',
    'Ce qu''il faut retenir : 31 marchés européens concernés dès le 24 août 2026, parmi lesquels la France, l''Allemagne, l''Espagne, l''Italie, la Suède, la Norvège, le Danemark, les Pays-Bas et l''Autriche. L''accès se fait dans un premier temps via des intermédiaires : l''équipe Ads Solutions d''OpenAI, des agences partenaires et des partenaires technologiques. Le libre-service […] L’article "ChatGPT Ads arrive en Europe : la publicité s’invite dans vos conversations avec l’IA" a été publié sur le site Abondance.',
    'Johan Sellitto',
    '2026-08-21T07:09:31.000Z',
    'OpenAI lance la publicité dans ChatGPT sur 31 marchés européens dès le 24 août 2026, dont la France, l''Allemagne et l''Espagne, dans un premier temps via l''équipe Ads Solutions d''OpenAI et des agences partenaires.',
    ARRAY['ia-geo']::text[],
    'majeur',
    'Ouverture d''un nouveau canal publicitaire directement dans les conversations IA, avec un impact potentiel sur la visibilité payante en environnement génératif.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'abondance'),
    'https://www.abondance.com/?p=2794297',
    'https://www.abondance.com/20260820-2794297-offre-emploi-google-confirmation-observations-discover.html',
    'Une offre d’emploi de Google confirme ce qu’on observe dans Discover',
    'L’entreprise a publié une fiche de poste pour un ingénieur senior dans son équipe « Discover Ranking », l’équipe qui fabrique le classement de votre flux. Parmi les prérequis, une ligne retient l’attention : le candidat doit savoir construire et déployer des « modèles de systèmes de recommandation (retrieval, prediction, ranking, embedding) en production ». […] L’article "Une offre d’emploi de Google confirme ce qu’on observe dans Discover" a été publié sur le site Abondance.',
    'Damien Andell',
    '2026-08-20T11:58:26.000Z',
    'Une fiche de poste publiée par Google pour l''équipe "Discover Ranking" mentionne explicitement des compétences en modèles de recommandation (retrieval, prediction, ranking, embedding) en production, confirmant les évolutions observées sur le classement de Discover.',
    ARRAY['technique']::text[],
    'mineur',
    'Indice indirect (fiche de poste) plutôt qu''une annonce officielle de changement d''algorithme.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'google-search-central'),
    '2026-07-29-Platform-properties-roll-out-globally,-plus-a-new-social-and-video-performance-guide',
    'https://developers.google.com/search/blog/2026/07/platform-properties-social-video-guide',
    'Platform properties roll out globally, plus a new social and video performance guide',
    'Earlier this month, we announced platform properties for Search Console, allowing you to track how your social and video posts on Instagram, TikTok, X, and YouTube perform on Google Search, Discover, and Google News. Today, platform properties are globally available to everyone.',
    null,
    '2026-07-29T00:00:00.000Z',
    'Les "platform properties" de Search Console, qui permettent de suivre les performances des contenus publiés sur Instagram, TikTok, X et YouTube dans Google Search, Discover et Google News, sont désormais disponibles pour tous.',
    ARRAY['technique']::text[],
    'mineur',
    'Nouvelle fonctionnalité de reporting dans Search Console, sans changement de classement.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'google-search-central'),
    '2026-07-07-See-how-content-from-social-and-video-platforms-performs-on-Google-Search',
    'https://developers.google.com/search/blog/2026/07/search-console-social-video-platforms',
    'See how content from social and video platforms performs on Google Search',
    'Content creators and publishers use many channels beyond their own websites to reach their audiences. As people gravitate toward firsthand perspectives and different content formats, we want to make it easier for site owners and creators&mdash;even those without their own website&mdash;to get a consolidated view of how all of their content is getting discovered on Search.',
    null,
    '2026-07-07T00:00:00.000Z',
    'Google détaille une nouvelle vue consolidée dans Search Console permettant de suivre comment les contenus publiés sur les réseaux sociaux et plateformes vidéo sont découverts via la Recherche Google, même sans site web propre.',
    ARRAY['technique']::text[],
    'mineur',
    'Documentation d''une fonctionnalité déjà annoncée, à visée pédagogique.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'google-search-central'),
    '2026-07-06-Search-Central-Deep-Dive-Europe-2026:-Apparently-we''re-going-to-Barcelona',
    'https://developers.google.com/search/blog/2026/07/search-central-live-deep-dive-europe-2026',
    'Search Central Deep Dive Europe 2026: Apparently we''re going to Barcelona',
    'We''re excited to officially announce the next stop for Search Central Live Deep Dive Europe 2026! Mark your calendars: based directly on your feedback, we''re headed to Barcelona, Spain, from September 30 to October 2, 2026.',
    null,
    '2026-07-06T00:00:00.000Z',
    'Google annonce que son prochain événement Search Central Live Deep Dive Europe se tiendra à Barcelone du 30 septembre au 2 octobre 2026.',
    '{}',
    'mineur',
    'Annonce logistique d''événement, sans contenu technique ou algorithmique.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'moz-blog'),
    'https://moz.com/blog/10-fan-outs-for-prompt-research-whiteboard-friday',
    'https://moz.com/blog/10-fan-outs-for-prompt-research-whiteboard-friday',
    '10 Fan-Outs for Prompt Research — Whiteboard Friday',
    'Google uses these 10 query fan-outs to split single prompts into multiple background searches.Learn how to map this behavior in this Whiteboard Friday with Tom Capper.',
    'Tom Capper',
    '2026-08-21T07:00:00.000Z',
    'Dans ce Whiteboard Friday, Tom Capper détaille dix "fan-outs" que Google utiliserait pour décomposer un prompt unique en plusieurs recherches en arrière-plan, et comment cartographier ce comportement.',
    ARRAY['ia-geo', 'technique']::text[],
    'mineur',
    'Analyse pédagogique d''un mécanisme IA, sans confirmation officielle de Google.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'moz-blog'),
    'https://moz.com/blog/should-we-stop-writing-with-ai',
    'https://moz.com/blog/should-we-stop-writing-with-ai',
    'Should We Stop Writing With AI?',
    'Should you stop writing with AI as detection, spam, and sameness grow? Learn how expert-led AI content builds trust, audience ownership, and lasting value for years.',
    'Chima Mmeje',
    '2026-08-20T07:00:00.000Z',
    'Face à la détection, au spam et à l''uniformisation des contenus IA, Moz explique comment une écriture assistée par IA mais pilotée par des experts permet de construire confiance, audience propre et valeur durable.',
    ARRAY['contenu', 'ia-geo']::text[],
    'mineur',
    'Position éditoriale et recommandations, pas un changement de plateforme.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'moz-blog'),
    'https://moz.com/blog/local-business-reviews-and-llms',
    'https://moz.com/blog/local-business-reviews-and-llms',
    'Are Reviews Shaping What LLMs Say About My Local Business?',
    'Discover how customer reviews directly influence what Large Language Models (LLMs) say about your local business in AI-powered search results and better understand how sentiment, volume, recency, and keyword relevance in reviews shape AI-generated recommendations.',
    'Jonathan Berthold',
    '2026-08-19T07:00:00.000Z',
    'Les avis clients influenceraient directement ce que les grands modèles de langage disent d''un commerce local, via leur volume, leur ancienneté, leur tonalité et les mots-clés qu''ils contiennent.',
    ARRAY['local-seo', 'ia-geo']::text[],
    'mineur',
    'Étude de corrélation, sans changement de plateforme confirmé.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'ahrefs-blog'),
    'https://ahrefs.com/blog/?p=203848',
    'https://ahrefs.com/blog/information-gain/',
    'What Is Information Gain in SEO? (and How To Add It to Your Content)',
    'Whether Google runs a literal information gain score is still unconfirmed. But whether or not it improves your ranking is almost irrelevant. You should care about information gain because it’s your differentiator. The extra effort you put into creating useful,… Read more ›',
    'Louise Linehan',
    '2026-08-20T15:39:55.000Z',
    'Que Google utilise ou non un score d''"information gain" reste incertain, mais l''article soutient que cette notion doit rester un objectif éditorial : apporter une valeur réellement différenciante plutôt que de reformuler l''existant.',
    ARRAY['contenu']::text[],
    'mineur',
    'Cadre conceptuel et bonnes pratiques éditoriales, pas une annonce ou un changement produit.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'ahrefs-blog'),
    'https://ahrefs.com/blog/?p=203682',
    'https://ahrefs.com/blog/claude-now-watermarks-everything-it-writes/',
    'Claude Now Watermarks Everything It Writes. Here’s What It Means for Marketers',
    'For most marketers, I don’t think so. Google has said for years that it doesn’t care how content is produced, only whether it exists to manipulate rankings. And our own research shows that AI-generated content already performs in search: 5.3%… Read more ›',
    'Ryan Law',
    '2026-08-14T13:39:21.000Z',
    'Claude tatoue désormais numériquement tous les textes qu''il génère ; selon Ahrefs, cela ne devrait pas changer grand-chose pour les marketeurs puisque Google affirme ne pas se soucier de la méthode de production du contenu.',
    ARRAY['ia-geo', 'contenu']::text[],
    'mineur',
    'Évolution côté outil IA avec un impact indirect et encore incertain sur le SEO.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'ahrefs-blog'),
    'https://ahrefs.com/blog/?p=203623',
    'https://ahrefs.com/blog/how-to-use-ai-in-marketing/',
    '37 Proven Ways to Use AI in Marketing',
    '37 proven ways to use AI in marketing, from SEO to international marketing, each one from a marketer who has done it and shown their working. Read more ›',
    'Ryan Law',
    '2026-08-13T08:32:36.000Z',
    'Une compilation de 37 usages concrets de l''IA en marketing, du SEO au marketing international, chacun documenté par un praticien ayant réellement mis en œuvre la méthode.',
    ARRAY['ia-geo']::text[],
    'mineur',
    'Guide de bonnes pratiques, pas une actualité ou un changement de plateforme.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'backlinko'),
    'https://backlinko.com/?p=196568',
    'https://backlinko.com/website-marketing',
    '7 Website Marketing Strategies for 2026',
    'Website marketing in 2026 no longer works the way it used to. Traditionally, it meant promoting your site to attract visitors and turn them into customers. Your website is still central. But much of the customer journey now happens beyond it. Before someone visits your site, they’ve often already checked AI tools, Reddit threads, and … The post 7 Website Marketing Strategies for 2026 appeared first on Backlinko.',
    'Yongi Barnard',
    '2026-08-19T23:53:56.000Z',
    'Le marketing de site web en 2026 ne se limite plus à attirer des visiteurs directs : une grande partie du parcours client passe désormais par les outils IA, Reddit ou d''autres canaux avant même la visite du site.',
    ARRAY['ia-geo', 'contenu']::text[],
    'mineur',
    'Constat de tendance et conseils stratégiques, sans annonce produit.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'backlinko'),
    'https://backlinko.com/?p=197073',
    'https://backlinko.com/brand-mentions',
    'Brand Mentions in 2026: How to Earn and Track Them Across the Web',
    'You can have an impressive website, great content, and a seamless user experience. But you might still be invisible to search engines and AI tools. That’s because Google and ChatGPT don’t just look at your website. They also look at what other credible sources say about your brand to understand who you are and whether … The post Brand Mentions in 2026: How to Earn and Track Them Across the Web appeared first on Backlinko.',
    'Shreelekha Singh',
    '2026-08-19T11:04:49.000Z',
    'Google et ChatGPT évaluent aussi une marque à travers ce que disent d''elle des sources tierces crédibles ; l''article explique comment gagner et suivre ces mentions de marque à travers le web.',
    ARRAY['netlinking', 'ia-geo']::text[],
    'mineur',
    'Guide méthodologique, pas un changement d''algorithme ou de plateforme.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'backlinko'),
    'https://backlinko.com/?p=197596',
    'https://backlinko.com/llm-prompt-tracking',
    'Prompt Tracking: How to Find (and Fix) Your AI Visibility Gaps',
    'Your brand could be ranking #1 on Google, but still be invisible to AI. Absent from conversations your customers are having with large language models (LLMs) about your category. Or worse, showing up inaccurately, with outdated or incorrect information that’ll hurt your sales. Without prompt tracking, you’d never know. Prompt tracking (sometimes called LLM visibility … The post Prompt Tracking: How to Find (and Fix) Your AI Visibility Gaps appeared first on Backlinko.',
    'Shannon Tien',
    '2026-08-13T21:23:04.000Z',
    'Une marque peut être première sur Google tout en restant invisible dans les réponses des IA conversationnelles ; l''article présente le "prompt tracking" pour détecter ces angles morts et les corriger.',
    ARRAY['ia-geo']::text[],
    'mineur',
    'Méthodologie et outillage de suivi, sans annonce de plateforme.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'ipullrank'),
    'https://ipullrank.com/?p=22291',
    'https://ipullrank.com/2026-fastest-growing-companies',
    'iPullRank Named to the 2026 Inc. 5000 List of America’s Fastest-Growing Private Companies',
    'NEW YORK, NY, August 11, 2026 – After 12 years of innovation, determination, and solving client challenges of all sizes, enterprise AI Search agency iPullRank is thrilled to announce its inclusion on the Inc. 5000 list of fastest-growing privately held companies in the United States. The Inc. 5000 ranks companies by overall revenue growth over a three-year […] The post iPullRank Named to the 2026 Inc. 5000 List of America’s Fastest-Growing Private Companies appeared first on iPullRank.',
    'Francine Monahan',
    '2026-08-11T11:00:00.000Z',
    'L''agence iPullRank figure au classement Inc. 5000 2026 des entreprises privées américaines à la croissance la plus rapide, après 12 ans d''activité dans le search IA.',
    '{}',
    'mineur',
    'Actualité d''entreprise, sans portée technique ou stratégique pour le secteur.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'ipullrank'),
    'https://ipullrank.com/?p=22204',
    'https://ipullrank.com/zero-click-behavior-analysis-q3-2026',
    'What 13 Billion Google Searches Reveal About Zero-Click Behavior',
    'Most clicks go to sites the searcher never named, Google absorbs about a third of Wikipedia’s would-be traffic but barely dents Reddit’s, and ChatGPT now pulls more of its clicks from ads than any other top destination. TL;DR Nearly half of Google searches now end without a click, but treating zero-click as a single number […] The post What 13 Billion Google Searches Reveal About Zero-Click Behavior appeared first on iPullRank.',
    'Cate Dombrowski',
    '2026-07-30T11:00:00.000Z',
    'Près de la moitié des recherches Google se terminent désormais sans clic ; Google absorbe environ un tiers du trafic potentiel de Wikipédia mais entame à peine celui de Reddit, tandis que ChatGPT tire déjà plus de clics de ses publicités que de toute autre source.',
    ARRAY['ia-geo']::text[],
    'majeur',
    'Données chiffrées à grande échelle sur l''évolution du zero-click, un indicateur structurant pour les équipes SEO.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'ipullrank'),
    'https://ipullrank.com/?p=22112',
    'https://ipullrank.com/ai-search-agency',
    'How We Reorganized our Agency Around AI Search',
    'Let’s be honest about where most marketing teams are right now. Traffic is disappearing in ways that are hard to explain in a report, attribution is getting confusing, and AI platforms are recommending competitors in categories where you’ve spent years building authority. Nobody asked for this (or planned for it). But it’s here, so how […] The post How We Reorganized our Agency Around AI Search appeared first on iPullRank.',
    'Francine Monahan',
    '2026-07-16T15:00:00.000Z',
    'Face à la baisse du trafic organique classique et à la recommandation de concurrents par les plateformes IA, iPullRank explique comment elle a réorganisé son agence autour du search IA.',
    ARRAY['ia-geo']::text[],
    'mineur',
    'Retour d''expérience organisationnel, pas une évolution produit ou algorithmique.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'growth-memo'),
    'https://www.growth-memo.com/p/growth-intelligence-brief-23',
    'https://www.growth-memo.com/p/growth-intelligence-brief-23',
    'Growth Intelligence Brief #23',
    'ZipRecruiter gives back July spike, YouTube slides 6th straight week, dictionaries surge, NYC.gov and StreetEasy crash, TheKitchn hits all-time high, Amazon climbs, Reddit stands still',
    'Kevin Indig',
    '2026-08-20T15:21:29.000Z',
    'Point hebdomadaire de trafic : ZipRecruiter perd son pic de juillet, YouTube recule pour la sixième semaine consécutive, les sites de dictionnaires progressent fortement, tandis qu''Amazon continue de grimper.',
    '{}',
    'mineur',
    'Suivi de tendances de trafic multi-sites, sans événement isolé à fort impact.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'growth-memo'),
    'https://www.growth-memo.com/p/slop-antibodies',
    'https://www.growth-memo.com/p/slop-antibodies',
    'Slop Antibodies',
    'The connection between Slop, watermarking and Commodity Content shows us the blueprint for successful content in the AI era',
    'Kevin Indig',
    '2026-08-17T07:54:02.000Z',
    'Kevin Indig relie le contenu de faible qualité généré en masse ("slop"), le tatouage numérique des IA et le "commodity content" pour dessiner ce qui fonctionnera dans le contenu à l''ère de l''IA.',
    ARRAY['ia-geo', 'contenu']::text[],
    'mineur',
    'Analyse de tendance et cadre stratégique, sans changement de plateforme.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'growth-memo'),
    'https://www.growth-memo.com/p/multiply-your-brand-authority',
    'https://www.growth-memo.com/p/multiply-your-brand-authority',
    'Multiply your brand authority',
    '4 tools that work together for brand authority multiplication',
    'Kevin Indig',
    '2026-08-14T09:23:19.000Z',
    'Quatre outils qui, combinés, permettent de démultiplier l''autorité de marque.',
    ARRAY['netlinking']::text[],
    'mineur',
    'Conseil stratégique et outillage, pas une actualité.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'onely'),
    'https://www.onely.com/?post_type=article&p=14404',
    'https://www.onely.com/blog/best-franchise-seo-agencies/',
    'Best Franchise SEO Agencies in 2026: An Engineering-Led Evaluation for AI Search Visibility',
    'Your traditional rankings look stable. Your franchise location pages still hold position for core local service queries. And yet organic […] The post Best Franchise SEO Agencies in 2026: An Engineering-Led Evaluation for AI Search Visibility appeared first on Onely.',
    'Bartosz Góralewicz',
    '2026-06-05T06:16:18.000Z',
    'Malgré des positions stables sur les requêtes locales classiques, la visibilité organique des enseignes en franchise recule ; Onely évalue les meilleures agences SEO spécialisées sous l''angle de la visibilité en recherche IA.',
    ARRAY['local-seo', 'ia-geo']::text[],
    'mineur',
    'Contenu de comparatif d''agences, à visée commerciale.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'onely'),
    'https://www.onely.com/?post_type=article&p=14401',
    'https://www.onely.com/blog/best-seo-agencies-for-pet-brands/',
    'Best SEO Agencies for Pet Brands in 2026: A GEO-First Evaluation',
    'Your competitors are named in Google AI Overviews when a pet owner asks about joint supplements for a senior dog. […] The post Best SEO Agencies for Pet Brands in 2026: A GEO-First Evaluation appeared first on Onely.',
    'Bartosz Góralewicz',
    '2026-06-05T06:09:56.000Z',
    'Comparatif d''agences SEO pour les marques du secteur animalier, évaluées sous un angle "GEO-first" alors que des concurrents apparaissent déjà nommés dans les AI Overviews de Google.',
    ARRAY['local-seo', 'ia-geo']::text[],
    'mineur',
    'Contenu de comparatif d''agences, à visée commerciale.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'onely'),
    'https://www.onely.com/?post_type=article&p=14398',
    'https://www.onely.com/blog/best-self-storage-seo-agencies/',
    'Best Self-Storage SEO Agencies in 2026: An AI-Search-Era Evaluation',
    'Your location pages rank on page one. Your Google Business Profiles are claimed and optimized. And yet, when a renter […] The post Best Self-Storage SEO Agencies in 2026: An AI-Search-Era Evaluation appeared first on Onely.',
    'Bartosz Góralewicz',
    '2026-06-05T05:51:09.000Z',
    'Même constat pour le secteur du self-stockage : bon positionnement classique mais absence dans les réponses IA ; Onely évalue les agences les mieux placées pour corriger ce point.',
    ARRAY['local-seo', 'ia-geo']::text[],
    'mineur',
    'Contenu de comparatif d''agences, à visée commerciale.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'aleyda-solis'),
    'https://www.aleydasolis.com/?p=94083',
    'https://www.aleydasolis.com/en/ai-search/third-party-citation-optimization-ai-search/',
    'Third-Party Citation Optimization Prioritization in an AI Search Era: A Framework + Worksheet',
    'Which third-party citations and platforms are actually worth investing in when the sources used by AI search platforms can change by vertical, prompt, market, platform and model release? Although it’s easy to target third-party citation optimization with “one trick pony” tactics to “be active on Reddit” or “create more YouTube videos”, this doesn’t take into ... Third-Party Citation Optimization Prioritization in an AI Search Era: A Framework + Worksheet La entrada Third-Party Citation Optimization Prioritization in an AI Search Era: A Framework + Worksheet se publicó primero en International ',
    'Aleyda Solis',
    '2026-08-20T10:11:06.000Z',
    'Aleyda Solis propose un cadre et une feuille de travail pour prioriser les citations tierces à cibler en recherche IA, alors que les sources utilisées varient selon le secteur, la requête, le marché et le modèle.',
    ARRAY['ia-geo', 'netlinking']::text[],
    'mineur',
    'Méthodologie et outil pratique, pas une annonce de plateforme.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'aleyda-solis'),
    'https://www.aleydasolis.com/?p=93909',
    'https://www.aleydasolis.com/en/ai-search/content-prioritization-ai-search/',
    'Content Prioritization in an AI Search Era: A Framework + Worksheet',
    'What type of content is still worth creating when AI platforms can answer queries without sending a click? AI answers are much more likely to fully satisfy the user’s need when they only want a quick explanation, and less likely when they still need proof, current or personalized data, a meaningful comparison, context specific guidance, ... Content Prioritization in an AI Search Era: A Framework + Worksheet La entrada Content Prioritization in an AI Search Era: A Framework + Worksheet se publicó primero en International SEO Consultant, Author & Speaker | Aleyda Solis.',
    'Aleyda Solis',
    '2026-08-06T14:02:58.000Z',
    'Un cadre pour décider quels contenus restent pertinents à produire quand les IA répondent directement aux requêtes simples, en se concentrant sur les besoins qui exigent preuve, données actuelles ou contexte spécifique.',
    ARRAY['contenu', 'ia-geo']::text[],
    'mineur',
    'Cadre stratégique éditorial, pas une actualité produit.',
    '2026-08-23T16:23:56.136Z'
  ),
(
    (select id from public.sources where slug = 'aleyda-solis'),
    'https://www.aleydasolis.com/?p=93832',
    'https://www.aleydasolis.com/en/ai-search/ai-search-citations/',
    'AI Search Is a 3rd-Party Citation Problem With an On-Page Corroboration Base: The Data Across SaaS, Ecommerce and Finance',
    'AI search is largely a 3rd-party citation problem, supported by an on-page corroboration base: your site owned pages establish accurate, accessible facts while social, community, publisher, review, marketplace and competitor sources validate, demonstrate, compare or challenge them. It’s then fundamental to establish a cross-functional operating framework: SEO coordinating with digital PR and social media to ... AI Search Is a 3rd-Party Citation Problem With an On-Page Corroboration Base: The Data Across SaaS, Ecommerce and Finance La entrada AI Search Is a 3rd-Party Citation Problem With an On',
    'Aleyda Solis',
    '2026-08-02T12:51:34.000Z',
    'D''après une analyse croisant SaaS, e-commerce et finance, la recherche IA repose largement sur la citation de sources tierces qui viennent corroborer les faits publiés sur le site, ce qui implique une coordination étroite entre SEO, RP digitales et réseaux sociaux.',
    ARRAY['ia-geo', 'netlinking']::text[],
    'mineur',
    'Étude de données et cadre stratégique, sans annonce de plateforme.',
    '2026-08-23T16:23:56.136Z'
  )
on conflict (url) do nothing;